### ISSUE TITLE
建议项目介绍中给出 demo 地址

### ISSUE THREAD

**Issue by junbaor** [lancer07/css3_Chi-biMaruko#1]

**Comment by lancer07** [comment]
谢谢您的宝贵建议，已在wiki里更新

**Comment by junbaor** [comment]
![图片描述](http://img.junbaor.com/201605091AB72D947C8BD6AE8C8283F4B4620F46.png)

wiki比较隐蔽,可以点这里直接填写 demo 网址，打开项目就能看到，随手就能点  :blush:

**Comment by lancer07** [comment]
原来如此，多谢指点
